# Site settings
title: raupach.me
email: raupach@me.com 
description: > # this means to ignore newlines until "baseurl:"
  A little blog about programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://raupach.me" # the base hostname & protocol for your site
twitter_username: raupach
github_username:  raupachz

# Build settings
markdown: kramdown
